name: test
on: [ push, pull_request ]
jobs:
  unit-test:
    name: Perform unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build tests
      run: make build-unit-tests
    - name: Run tests
      run: make run-unit-tests
