name: test
on: [ push, pull_request ]
jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build unit tests
      run: make build/unit-test.out
    - name: Run unit tests
      run: ./build/unit-test.out
  fuzz-test:
    name: Run fuzz tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build fuzz tests
      run: make build/fuzz-test.out
    - name: Run fuzz tests
      run: ./build/fuzz-test.out
