name: test
on: [ push, pull_request ]
jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build unit tests
      run: make bin/unit_test.out
    - name: Run unit tests
      run: ./bin/unit_test.out
  fuzz-test:
    name: Run fuzz tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build fuzz tests
      run: make bin/fuzz_test.out
    - name: Run fuzz tests
      run: ./bin/fuzz_test.out
