name: test
on: [ push, pull_request ]
jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build unit tests
      run: make bin/unit_test.out
    - name: Run unit tests
      run: ./bin/unit_test.out
  fuzz-test:
    name: Run fuzz tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build fuzz tests
      run: make bin/linear_fuzz_test.out bin/grid_fuzz_test.out
    - name: Run linear fuzz tests
      run: ./bin/linear_fuzz_test.out
    - name: Run grid fuzz tests
      run: ./bin/grid_fuzz_test.out
