name: test
on: [ push, pull_request ]
jobs:
  unit-test:
    name: Perform unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build tests
      run: make build/unit-test.out
    - name: Run tests
      run: ./build/unit-test.out
